services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    network_mode: bridge
    environment:
      - INTERFACE=eth0
    cap_add:
      - NET_RAW
    privileged: true

  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    network_mode: bridge
    environment:
      - INTERFACE=eth0
    privileged: true